import PastColorDisplay from "js/components/PastColorDisplay";

function Past() {
    return (
        <div className="past page-padding page-min-height">
            <div className="content">
                <h2>Past Colors</h2>
                <p>Here you can find all of the previous hex code color schemes generated by the ESBLights API.</p>
                <PastColorDisplay />
            </div>
        </div>
    )
}

export default Past;